# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "252213e3efdacfef45133d30767b038b"
application_url = "https://elsewhere-organ-sympathy-commodity.trycloudflare.com"
embedded = true
name = "qr"
handle = "qr-58"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://elsewhere-organ-sympathy-commodity.trycloudflare.com/auth/callback",
  "https://elsewhere-organ-sympathy-commodity.trycloudflare.com/auth/shopify/callback",
  "https://elsewhere-organ-sympathy-commodity.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "test-qr-test.myshopify.com"
automatically_update_urls_on_dev = true
